Repository Ayobami6/MeetDevs, pull requests merged in 2023-10, with the labels that each got.

#1 project codebase setup
  .github/workflows/lint.yml
  client/.eslintrc.cjs
  client/.gitignore
  client/README.md
  client/index.html
  client/package.json
  client/public/vite.svg
  client/src/App.css
  client/src/App.tsx
  client/src/assets/react.svg
  client/src/index.css
  client/src/main.tsx
  client/src/vite-env.d.ts
  client/tsconfig.json
  client/tsconfig.node.json
  client/vite.config.ts
Labels: setup

#7 Connect project to mongoose database
  client/package-lock.json
  package-lock.json
  server/.eslintrc.cjs
  server/index.ts
  server/package-lock.json
  server/package.json
Labels: enhancement

#53 B dev
  server/errors/customError.ts
  server/index.ts
  server/pagination/talentPagination.ts
  server/routes/talentPaginationRoute.ts
  server/test/talentControllers.test.ts
Labels: enhancement, feature

#79 B dev
  .prettierrc
  client/package-lock.json
  client/src/actions/education.ts
  client/src/components/DropDown/DropDown.css
  client/src/components/DropDown/DropDown.tsx
  client/src/components/Loading/Submit.tsx
  client/src/components/Navbar/TalentNav.tsx
  client/src/pages/Landing-Page/index.tsx
  server/controllers/employerController.ts
  server/controllers/offerController.ts
  server/controllers/talentController.ts
  server/index.ts
  server/interfaces/education.ts
  server/test/routes/offers.test.ts
  server/test/routes/talentControllers.test.ts
  server/test/talentControllers.test.ts
Labels: feature
